"""initial

Revision ID: 067388bff907
Revises:
Create Date: 2025-05-01 14:31:47.956410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067388bff907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
