"""initial

Revision ID: e193b5d44c2d
Revises: 473fcce94ff6
Create Date: 2025-05-01 14:42:01.515216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e193b5d44c2d'
down_revision = '473fcce94ff6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###